[build-system]
requires = ["setuptools>=40.8.0", "wheel", "cffi"]
build-backend = "setuptools.build_meta"

[tool.autopep8]
max_line_length = 80

[tool.cibuildwheel]
build-verbosity = "1"
test-requires = ["pytest"]
test-command = "bash {project}/python/test-wheel.sh {project}"
